[package]
name = "solana-poc"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
owo-colors = "4.0.0"
solana-logger = "2.0.5"
solana-program = "2.0.5"
solana-poc-framework = {path = "../solana-poc-framework"}
spl-token = { version = "*", features = ["no-entrypoint"] }

[lib]